#!/usr/bin/env python3
"""Axis windows and plotted quantities for every paper figure.

Pure data and text, with no matplotlib import. The drawing scripts read their
limits from here, and the prose reads the same values through the macros in
generated/figure-spec.tex, so a caption cannot describe a window that the
figure does not draw. A clipped window omits the marks outside it and counts
them in the panel title. Bounds are bare numbers; use them in math mode.

``python3 figure_spec.py --check`` compares the committed macro file with a
fresh rendering. ``--write`` writes it. Emitters call ``write_macros``.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path

PAPER = Path(__file__).resolve().parents[1]
GENERATED = PAPER / "generated"
MACRO_NAME = "figure-spec.tex"

# retention-bytes.pdf: one mark per lineage, its retention level at size 4n,
# against log10 charged bytes. Levels outside this window are omitted and
# counted in the panel title.
Y_LIM = (-1.5, 1.6)
# paired-cdf.pdf top row and mfs-v3-paired.pdf: sorted paired retention
# differences. Differences outside this window are counted in the panel title.
PAIRED_X_LIM = (-1.5, 1.5)
# teaser.pdf: Hodges-Lehmann paired differences per auditor. A difference outside
# the window is drawn at the nearer edge as an arrow with its value printed.
TEASER_X_LIM = (-0.3, 0.5)
# teaser.pdf rows sit at 0..k-1; this margin pads the first and last row.
TEASER_ROW_PAD = 0.6
# paired-cdf.pdf bottom strip: the Friedman average rank of each method.
RANK_X_LIM = (0.8, 4.3)
RANK_Y_LIM = (-0.9, 0.7)
# retention-bars.pdf and mfs-v3-retention-bars.pdf: bar medians and intervals.
RETENTION_BARS_Y_LIM = (-0.42, 1.22)
MFS_V3_BARS_Y_LIM = (-0.28, 1.18)
# loss-curves.pdf: per-step lineage medians on a log axis.
LOSS_Y_LIM = (3e-4, 0.7)


@dataclass(frozen=True)
class FigureSpec:
    """One figure. ``window`` is None when matplotlib chooses the limits."""

    script: str
    quantity: str
    axis: str | None
    window: tuple[float, float] | None = None
    clipped: bool = False
    scale: str = "linear"
    macro: str | None = None


FIGURES = {
    "teaser.pdf": FigureSpec(
        "v2_figures.py", "paired retention difference", "x", TEASER_X_LIM, True, macro="Teaser"),
    "pareto.pdf": FigureSpec(
        "v2_figures.py", "CatBoost retention level against median charged bytes", "x", scale="log"),
    "retention-bytes.pdf": FigureSpec(
        "render_figures.py", "retention level", "y", Y_LIM, True, macro="Scatter"),
    "paired-cdf.pdf": FigureSpec(
        "render_figures.py", "paired retention difference", "x", PAIRED_X_LIM, True, macro="Paired"),
    "mfs-v3-paired.pdf": FigureSpec(
        "mfs_v3_table.py", "paired retention difference", "x", PAIRED_X_LIM, True, macro="MfsPaired"),
    "retention-bars.pdf": FigureSpec(
        "render_figures.py", "CatBoost retention median", "y", RETENTION_BARS_Y_LIM),
    "mfs-v3-retention-bars.pdf": FigureSpec(
        "mfs_v3_table.py", "retention median", "y", MFS_V3_BARS_Y_LIM),
    "loss-curves.pdf": FigureSpec(
        "render_figures.py", "hidden-basis MSE", "y", LOSS_Y_LIM, scale="log"),
    "retained-matched-eight.pdf": FigureSpec(
        "retained_evidence.py", "retention and distance MIA AUC medians", "x"),
    "architecture.pdf": FigureSpec("figures/architecture.tex", "pipeline diagram", None),
}

_MACRO = re.compile(r"\\newcommand\{\\([A-Za-z]+)\}\{([^{}]*)\}")


def bound_tex(value: float) -> str:
    """Shortest decimal for a bound. The same float always prints the same text."""
    text = repr(float(value))
    return text[:-2] if text.endswith(".0") else text


def macro_values() -> dict[str, str]:
    """Macro name to body for every clipped figure with a macro stem."""
    values = {}
    for name, spec in FIGURES.items():
        if spec.macro is None:
            continue
        if not spec.clipped or spec.window is None or spec.axis not in ("x", "y"):
            raise ValueError(f"{name} names a macro without a clipped window")
        stem = "Fig" + spec.macro
        axis = spec.axis.upper()
        values[stem + "Quantity"] = spec.quantity
        values[stem + axis + "Lo"] = bound_tex(spec.window[0])
        values[stem + axis + "Hi"] = bound_tex(spec.window[1])
    return values


def macros_tex() -> str:
    lines = ["% Generated by figure_spec.py. Bounds are bare numbers for math mode.\n"]
    for name, body in macro_values().items():
        lines.append(f"\\newcommand{{\\{name}}}{{{body}}}\n")
    return "".join(lines)


def parse_macros(text: str) -> dict[str, str]:
    """Macro bodies from a generated file. A repeated name is an error."""
    found = {}
    for name, body in _MACRO.findall(text):
        if name in found:
            raise ValueError(f"{name} is defined twice")
        found[name] = body
    return found


def macro_failures(text: str) -> list[str]:
    """Differences between a macro file and the spec, by name."""
    failures = []
    found = parse_macros(text)
    expected = macro_values()
    for name, body in expected.items():
        if name not in found:
            failures.append(f"{name} is missing")
        elif found[name] != body:
            failures.append(f"{name} disagrees with figure_spec.py")
    for name in sorted(set(found) - set(expected)):
        failures.append(f"{name} is not in figure_spec.py")
    if not failures and text != macros_tex():
        failures.append(f"{MACRO_NAME} bytes differ from a fresh rendering")
    return failures


def write_macros(out_dir: Path | None = None) -> Path:
    """The emitter hook. Writes generated/figure-spec.tex and returns its path."""
    path = Path(GENERATED if out_dir is None else out_dir) / MACRO_NAME
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(macros_tex())
    return path


def check_macros(out_dir: Path | None = None) -> list[str]:
    path = Path(GENERATED if out_dir is None else out_dir) / MACRO_NAME
    if not path.is_file():
        return [f"{MACRO_NAME} is missing; call figure_spec.write_macros from the emitter"]
    return macro_failures(path.read_text())


def main(argv=None) -> int:
    args = sys.argv[1:] if argv is None else list(argv)
    if "--check" in args:
        failures = check_macros()
        print("\n".join(failures) if failures else "figure spec macros match")
        return 1 if failures else 0
    if "--write" in args:
        print(write_macros())
        return 0
    sys.stdout.write(macros_tex())
    return 0


if __name__ == "__main__":
    sys.exit(main())
